<?php
/***************************************************************************
 *
 * 	----------------------------------------------------------------------
 * 						DO NOT EDIT THIS FILE
 *	----------------------------------------------------------------------
 * 
 *  					Copyright (C) Themify
 * 						http://themify.me
 *
 ***************************************************************************/

$theme_includes = apply_filters( 'themify_theme_includes',
	array(	'themify/themify-database.php',
			'themify/class-themify-config.php',
			'themify/themify-utils.php',
			'themify/themify-config.php',
			'themify/themify-modules.php',
			'theme-options.php',
			'theme-modules.php',
			'theme-functions.php',
			'custom-modules.php',
			'custom-functions.php',
			'themify/themify-widgets.php' ));
			
foreach ( $theme_includes as $include ) { locate_template( $include, true ); }

/*Login*/

// Estização de página de login
function login_styles() { ?>
    <style type="text/css">
    body{background: #900 url('<?php echo get_stylesheet_directory_uri(); ?>/images/login-bg.png') repeat scroll center bottom ;}
    .login h1 a {width: 220px;height:80px;display: inline-block;background: url('<?php echo get_stylesheet_directory_uri(); ?>/images/logo-login-wp.png') no-repeat;}
    .login form {background: #eee;border-radius:4px;}
    .login label {font-size: 17px;color: #555;}
    .login form .input{background: #06A25F;box-shadow:none;border-radius: 4px;border: 1px solid #0B8E55;color: #fff;}
    .login form .input:hover, .login form .input:focus{background: #000;}
    .login .button-primary, .login .button-group.button-large .button, .login .button.button-large{height: 40px;padding: 0 20px;display: inline-block;box-shadow: none;border: none;background: #000;}
    .login .button-primary:hover {background: #069;}
    .login .forgetmenot{margin-top: 10px;}
    .login #nav a, .login #backtoblog a {color: #fff;}
    .login #nav a:hover, .login #backtoblog a:hover{text-decoration: underline;color: #fff;}
    </style>
<?php }
add_action('login_enqueue_scripts', 'login_styles');
 
// Link logo login
function my_login_logo_url() {
    return get_bloginfo( 'url' );
}
add_filter( 'login_headerurl', 'my_login_logo_url' );
 
// Mudar nome ao passar o mouse
function my_login_logo_url_title() {
    return 'Antunes Ramos Blog';
}
add_filter( 'login_headertitle', 'my_login_logo_url_title' );
?>
